### ISSUE TITLE
The deleted user's placeholder username label shouldn't allow navigation

### ISSUE THREAD

**Issue by ZeeshanZulfiqarAli** [rysolv/rysolv#104]
## Description

When a user has deleted their account after creating a issue, or commenting on one, their name is replaced with **[deleted]** label which still allows navigation to the deleted user's profile.

## Steps to reproduce

1. Open an issue.
2. Comment on it.
3. Delete your account.
4. Go back to that issue you created.

**Expected behavior**
The **[deleted]** label should not be clickable. Clicking on it leads to a page which shows 404. This should be prevented.

**Screenshots**
The deleted label is clickable in both of these instances:

**Issue opened by deleted user:**

![Issue opened by deleted user](https://user-images.githubusercontent.com/32417658/122291927-d7168080-cf0e-11eb-86ef-e537d0d25a38.png)

**Comment by a deleted user on a issue:**

![Comments on issue](https://user-images.githubusercontent.com/32417658/122292024-f4e3e580-cf0e-11eb-9e5d-1ed610aead3c.png)

**Clicking on the label always leads to a 404 page (as expected):**
![image](https://user-images.githubusercontent.com/32417658/122293869-e26aab80-cf10-11eb-91ec-de1a0ed42db2.png)

**Comment by annapo23** [comment]
Great find, Zeeshan! Definitely something we can action on.

**Comment by mucyildiz** [comment]
I can try and take this one if that's alright

**Comment by tylermaran** [comment]
@mucyildiz yea of couse! 

For this one you'll need to set up the environment to really test it out. 

The easiest way for me to walk you through that (and send some env variables) is if you can hop on the discord server ([invite link](https://discord.gg/axCNYAXk)

Generally the process will be: 
- Fork the repo
- Check out a branch from `dev` formatted with your initials / task. Something like: 
    - `git checkout dev`, `git pull`
    - `git checkout -b TM/fix-deleted-user-link`
- Follow instructions in the readme to get project running
    - if you run into problems here, please let me know so we can improve the readme
- Make the changes, test a couple scenarios
- Open a pull reqest with your branch against rysolv/dev
- I'll take a look, test it myself, and either propose changes or merge it in
- Done!

**Comment by tylermaran** [comment]
Released with #117
