### ISSUE TITLE
Are the "good first issue" issues resolved?

### ISSUE THREAD

**Issue by Dev-kris** [rysolv/rysolv#111]
Hi, I found your repo while looking for an open source project to contribute to. 

I am a very new react developer so to get some real world/ collaborative practice would be great for me! I saw both of the 'good first issue' tickets already had people working on them and don't know the etiquette of also offering or seeing if they abandoned. 

If any other beginner/first issues come up, I would be eager to take part!

Thanks a lot!

**Comment by tylermaran** [comment]
Hey @Dev-kris! They are right now, but I didn't expect so many participants. 

I can definitely generate a couple more good ones tonight. I'll add them to the issues page, and then ping you here.

**Comment by Dev-kris** [comment]
Thanks a lot!

**Comment by tylermaran** [comment]
Hey @Dev-kris I've got a new issue you can try out: https://github.com/rysolv/rysolv/issues/123
