### ISSUE TITLE
Remove the date from user card

### ISSUE THREAD

**Issue by tylermaran** [rysolv/rysolv#112]
This one should be pretty straight forward. I'd like to remove the 'Member since' line from the user cards. 

![image](https://user-images.githubusercontent.com/30934424/125846124-3faa9312-37f9-410f-a559-ed3690f577a6.png)

All the code should be here: https://github.com/rysolv/rysolv/tree/master/app/components/Users/Card

**Comment by adityagoel28** [comment]
Hii. I would like to try this
Thank you.
