### ISSUE TITLE
User Session not preserved in New Tab

### ISSUE THREAD

**Issue by cstayyab** [rysolv/rysolv#14]
## Description

Each tab in a same window of Browser requires separate Sign In every time

## Steps to reproduce

Steps to reproduce the behavior (include browser):
1. Open Mozilla Firefox
2. Go to `https://rysolv.com/signin`
3. Login to using Email and Password 
4. You will be redirected to `/issues`
5. Ctrl+Click on First Issue in the list
6. A new tab will open and you will notice in the top right corner two links to `Sign Up` and `Sign In` 

**Expected behavior**
Current Logged in User is being shown in the top right corner

**Screenshots**

1. Tab 1 (Logged In)
![Screenshot of Tab 1](https://user-images.githubusercontent.com/29598866/102966694-340e1c80-4512-11eb-8dfd-d77f718ab922.png)

2. Tab 2 (Not Logged In)
![image](https://user-images.githubusercontent.com/29598866/102966771-599b2600-4512-11eb-8340-83c843b84460.png)

**Comment by tylermaran** [comment]
Hey @cstayyab. This was resolved with some authentication changes we did a couple weeks ago. 
The cookie was incorrectly set as a session cookie. So cleared when you closed the tab. 

Thanks for the detailed issue.
