### ISSUE TITLE
Get repos query is duplicating dollar amounts.

### ISSUE THREAD

**Issue by tylermaran** [rysolv/rysolv#148]
Just noticed looking at this repo. 
This is likely something in the getRepos query (https://github.com/rysolv/rysolv/blob/master/server/db/queries/repos/getRepos.js)

I think it's just the LEFT JOIN vs JOIN on payments.
But needs a bit more exploration. 

![image](https://user-images.githubusercontent.com/30934424/132060737-91672b66-f458-42c6-b5f1-5c9be037f83c.png)

![image](https://user-images.githubusercontent.com/30934424/132060791-33a400ab-5d7b-47d6-8213-fc3530fcdacd.png)

**Comment by wilhsie** [comment]
Hey @tylermaran can I take this one?

**Comment by wilhsie** [comment]
If so, I just have a question..  How do I recreate this bug?  / what should the expected result be?

**Comment by bjorn** [comment]
Maybe worth noting that this bug does not appear to affect the "Price Range" slider in the sidebar:

![image](https://user-images.githubusercontent.com/531764/147110855-0e94c1d3-8936-49c1-91ac-083d32bbd566.png)

**Comment by ZeeshanZulfiqarAli** [comment]
@tylermaran can you please tell if you're looking into this one? or i can?

**Comment by tylermaran** [comment]
Hey @ZeeshanZulfiqarAli! Go for it! I'd just recommend branching off of master instead of dev.

And thanks @bjorn for the bounty!

**Comment by tylermaran** [comment]
Looks like it's working to me! I'll go ahead and merge it in.
![image](https://user-images.githubusercontent.com/30934424/147594071-7e9d2a56-a55e-48f2-ba5d-aaacd3461cb7.png)
