### ISSUE TITLE
Make it clearer that the website is open source and link to it's repository

### ISSUE THREAD

**Issue by wiki-me** [rysolv/rysolv#16]
**Is your feature request related to a problem? Please describe.**
Looking at the website you can't see that it is open source, and you can't see where it's repository is (which might hurt the competitive advantage this site has by being open source).

**Describe the solution you'd like**
Just provide a link to the repository at the end of the front page.

**Describe alternatives you've considered**
Maybe put it in a "about" page, or just have something saying "fork me on github".

**Comment by tylermaran** [comment]
Added the Github link in pr #45
