### ISSUE TITLE
No HTML `theme-color` meta tag in app/index.html.

### ISSUE THREAD

**Issue by KyleSmith0905** [rysolv/rysolv#240]
## Description

The site doesn't have a `theme-color` meta tag.
```
<meta name="theme-color" content="{COLOR}">
```
Some browsers use the `theme-color` to frame the site.

## Steps to reproduce

Go to https://rysolv.com/dashboard on Safari with an iPhone

**Expected behavior**
The top of the page should blend in with the padding that Safari adds under the status bar.

**Screenshots**
![image](https://user-images.githubusercontent.com/65096948/167744773-b39fa31c-61e9-4c72-8db1-444ee1ebe5fd.jpeg)

**Comment by KyleSmith0905** [comment]
This is what GitHub looks like for reference ![image](https://user-images.githubusercontent.com/65096948/167745004-7562ec26-1054-4b3c-ac93-89956ff7d8c5.jpeg)

**Comment by tylermaran** [comment]
Closed with #241
