### ISSUE TITLE
Filter out deleted users in the attempting/watching count

### ISSUE THREAD

**Issue by tylermaran** [rysolv/rysolv#88]
## Description

We should filter out deleted users from the attempt / watch list
<img src="https://user-images.githubusercontent.com/30934424/117852156-0faea480-b255-11eb-97e6-a00e892a0c89.png" width=500 />

## Steps to reproduce

- Create a user account
- Start attempting/watching a few issues
- Delete your account
- Check the attempt / watch list

## Fix

~~Filter for the users `is_deleted` flag in the following files:~~
~~- https://github.com/rysolv/rysolv/blob/master/server/db/queries/issues/getIssueAttemptList.js~~
~~- https://github.com/rysolv/rysolv/blob/master/server/db/queries/issues/getIssues.js~~
~~- https://github.com/rysolv/rysolv/blob/master/server/db/queries/issues/getOneIssue.js~~
~~- Check the `issueCardValues` in ./constants for `getIssues.js` and `getOneIssue.js`~~

- In the delete user function, also remove the attempting & watching rows
  - https://github.com/rysolv/rysolv/blob/master/server/graphql/resolvers/users/deleteUser.js
- Create two new functions in db/queries/attempting & db/queries/watching
  - `removeAttempting` / `removeWatching`

## Claim this issue on rysolv
https://rysolv.com/issues/detail/f81fd17d-4ef8-421d-90cd-da3281ddfe16

**Comment by tylermaran** [comment]
After some discussion, I think we are addressing the wrong problem here. The user shouldn't exist in the attempting / watching table if they delete their account. 

Also filtering required an extra join on the issues query, which was adding some meaningful time to the query. 

I've updated the fix in the original issue:
- In the delete user function, also remove the attempting & watching rows
  - https://github.com/rysolv/rysolv/blob/master/server/graphql/resolvers/users/deleteUser.js
- Create two new functions in db/queries/attempting & db/queries/watching
  - removeAttempting / removeWatching

The updated queries should be pretty simple. 

`DELETE FROM attempting WHERE user_id = $1`

@ZeeshanZulfiqarAli would you like to handle this?

**Comment by ZeeshanZulfiqarAli** [comment]
@tylermaran Sure, I'll get started on it
