### ISSUE TITLE
Cannot unsubscribe from notifications

### ISSUE THREAD

**Issue by novemberborn** [rysolv/rysolv#93]
I got a "3 new issues for you!" email notification. There is no unsubscribe link, nor can I find this in the settings.

As a maintainer, more issues is not what I'm looking forward to 😉

**Comment by tylermaran** [comment]
I believe it! Thanks for raising an issue.

We'll definitely have an unsubscribe link embedded in the next rounds of emails. And we're working on account level email options right now.

I'll also go ahead and unsubscribe you manually for now.

**Comment by tylermaran** [comment]
closed with #81

**Comment by tylermaran** [comment]
closed with #81
